travis:
  secure:
    BINSTAR_TOKEN: oA9dWHohzudjIqYDdZYOZspT8BJFcVh2WRU4effftyp0YFhFLZhpcmQrmkOwE0EdLJ+7Tg7Ft66sbS9mtZXTAgv8BT2QWMuqQ51oQgNRHTtaniNyfbbWQFyisex/eywoqxKpwH1UFiUYMb/H3uj1UU54fG1jQlFW746TTzjxLmALfZs7INHlgTkjXUceDcurq5NR0uiFwtx6tjP88JkndlaFVumSEO474H8hjEqSEZojMq1DRQqbffEyCKg3Ib+t5DN7j2JNQ+v0ftFxaKWNspbLGGkSwAOXKPDDwFXEl9KXkiaTnLAJP0nEMa4ClDHObigg6JwTx0rGQ+n1PkhxeUyHOIvKQJdxaOIjIiuOswDGEXmyTleouo2SxzWKF9uEttC5kH3AsBDOwVe7pszHCVeRDiEhs8+WGnsvxlxh7vm8msS4zVSGl4EM1rnHWsKLN9POfb66wRJ1FGtNJ4vL+WG/KkK5WKb3VHA/6K4D/AKgXvpzKddVoFb2H3XiNixUbPP0FOAG2GJYJ3csJK4FvPy5qwRpw7nEivMEzJRCvuukqXeIvPd8CiyDoYlhmbayQc0PWhjyUgWaZ2KYs2NfQrv4WMN3gP65p5PmP+//7qrmhL6ucQJ//5H04xqBrPzLmGouRLqlyRmmR/odrIXb+GKTI48uHXDaA4G6eOCWue0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
